var data = {
    "主页":"<html><div style='background:red'>我是主页</div></html>",
    "我的":{"name":"张三","age":"18","sex":"男"},
    "默认":"<html><div>no such page</div></html>",
    users:[{
        userID:'001',
        account:'123456',
        password:'123456'
    },{
        userID:'002',
        account:'zhansan',
        password:'1234567'
    },{
        userID:'003',
        account:'lisi',
        password:'1234568'
    },{
        userID:'004',
        account:'wangwu',
        password:'1234569'
    },{
        userID:'005',
        account:'zhaoliu',
        password:'123456'
    },{
        userID:'006',
        account:'wangxiaoer',
        password:'123456'
    }],
    dataList:[{
        listName:'每日推荐',
        content:[{
            rank:1,
            number:01,
            name:'猫',
            cancelNum:8,
            sum:24
        },{
            rank:2,
            number:02,
            name:'猫',
            cancelNum:8,
            sum:24
        },{
            rank:3,
            number:03,
            name:'猫',
            cancelNum:8,
            sum:24
        },{
            rank:4,
            number:04,
            name:'猫',
            cancelNum:8,
            sum:24
        },{
            rank:5,
            number:05,
            name:'猫',
            cancelNum:8,
            sum:24
        },{
            rank:6,
            number:06,
            name:'猫',
            cancelNum:8,
            sum:24
        }]
    },{
        listName:'投票排行',
        content:[{
            rank:1,
            number:01,
            name:'咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:2,
            number:02,
            name:'咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:3,
            number:03,
            name:'咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:4,
            number:04,
            name:'咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:5,
            number:05,
            name:'咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:6,
            number:06,
            name:'咪咪',
            cancelNum:8,
            sum:24
        }]        
    },{
        listName:'TOP300',
        content:[{
            rank:1,
            number:01,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:2,
            number:02,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:3,
            number:03,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:4,
            number:04,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:5,
            number:05,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        },{
            rank:6,
            number:06,
            name:'猫咪咪',
            cancelNum:8,
            sum:24
        }]
    }],
    history:[
        {
            userId:001,
            data:[
                    {
                        testPaperName:'高级程序开发1',  
                        testTime:'1499212800000',
                        score:90
                    },
                    {
                        testPaperName:'高级程序开发2',  
                        testTime:'1499299200000',
                        score:92.5
                    },
                    {
                        testPaperName:'高级程序开发3',  
                        testTime:'1499385600000',
                        score:95
                    },
                    {
                        testPaperName:'高级程序开发4',  
                        testTime:'1499472000000',
                        score:92.5
                    },
                    {
                        testPaperName:'高级程序开发5',  
                        testTime:'1499558400000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发6',  
                        testTime:'1499644800000',
                        score:95
                    },
                    {
                        testPaperName:'高级程序开发周考一',  
                        testTime:'1499731200000',
                        score:92.5
                    },
                    {
                        testPaperName:'高级程序开发8',  
                        testTime:'1499817600000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发9',  
                        testTime:'1499904000000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发10',  
                        testTime:'1499990400000',
                        score:95
                    },
                    {
                        testPaperName:'高级程序开发11',  
                        testTime:'1500076800000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发12',  
                        testTime:'1500163200000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发13',  
                        testTime:'1500249600000',
                        score:92.5
                    },
                    {
                        testPaperName:'高级程序开发周考二',  
                        testTime:'1500336000000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发15',  
                        testTime:'1500422400000',
                        score:90
                    },
                    {
                        testPaperName:'高级程序开发16',  
                        testTime:'1500508800000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发17',  
                        testTime:'1500595200000',
                        score:95
                    },
                    {
                        testPaperName:'高级程序开发18',  
                        testTime:'1500681600000',
                        score:90
                    },
                    {
                        testPaperName:'高级程序开发19',  
                        testTime:'1500768000000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发20',  
                        testTime:'1500854400000',
                        score:100
                    }
                ]
        },
        {
            userId:002,
            data:[
                    {
                        testPaperName:'高级程序开发1',  
                        testTime:'1499212800000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发2',  
                        testTime:'1499299200000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发3',  
                        testTime:'1499385600000',
                        score:95
                    },
                    {
                        testPaperName:'高级程序开发4',  
                        testTime:'1499472000000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发5',  
                        testTime:'1499558400000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发6',  
                        testTime:'1499644800000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发周考一',  
                        testTime:'1499731200000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发8',  
                        testTime:'1499817600000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发9',  
                        testTime:'1499904000000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发10',  
                        testTime:'1499990400000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发11',  
                        testTime:'1500076800000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发12',  
                        testTime:'1500163200000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发13',  
                        testTime:'1500249600000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发周考二',  
                        testTime:'1500336000000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发15',  
                        testTime:'1500422400000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发16',  
                        testTime:'1500508800000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发17',  
                        testTime:'1500595200000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发18',  
                        testTime:'1500681600000',
                        score:100
                    },
                    {
                        testPaperName:'高级程序开发19',  
                        testTime:'1500768000000',
                        score:97.5
                    },
                    {
                        testPaperName:'高级程序开发20',  
                        testTime:'1500854400000',
                        score:100
                    }
                ]
        }                                    
    ],
    stuMsg:[
        {userId:'',
        msg:{   
        }},
        {userId:'',
        msg:{   
        }},
        {userId:'',
        msg:{   
        }}
    ]  
}

module.exports = data;